config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  get "new_notice" => 'posts#new_notice', as: 'new_post_notice'

  get "edit_notice/:id" => "posts#edit_notice", as: 'edit_post_notice'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root "home#index"

  get 'home/index' => 'home#index', as: 'index'

  get 'home/about' => 'home#about', as: 'about'

  get 'home/activities' => 'home#activities', as: 'activities'

  get 'home/recruit' => 'home#recruit', as: 'recruit'

  get 'home/contact' => 'home#contact', as: 'contact'

  get 'home/members' => 'home#members', as: 'members'

  get 'search' => "posts#search", as: 'search'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg bg-transparent navbar1 ">

  <div class="navbar-collapse" id="navbarNav">
      <ul class="navbar-nav h5">
        <li class="nav-item">  
         <%= link_to image_tag("nextlogo.png", alt: "index"), index_path, class: "nav-link nav-special" %>
        </li>
  </div>

  <div class="navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav h5 ">
      <li class="nav-item nav-item1">
        <%= link_to 'ABOUT', about_path, class: "nav-link"%>
      </li>
      <li class="nav-item nav-item1">
        <%= link_to 'ACTIVITIES', activities_path, class: "nav-link"%>
      </li>
      <li class="nav-item nav-item1">
        <%= link_to 'RECRUIT', recruit_path, class: "nav-link"%>
      </li>
      <li class="nav-item nav-item1">
        <%= link_to 'MEMBERS', members_path, class: "nav-link"%>
      </li>
        <% changedPath = (user_signed_in?) ? posts_path : new_user_session_path %>
      <li class="nav-item nav-item1">
        <%= link_to 'MEMBER LOUNGE', changedPath, class: "nav-link"%>
      </li>
      <li class="nav-item nav-item1">
       <%= link_to image_tag("phonelogo.png", alt: "contact"), contact_path, class: "nav-link" %>
      </li>

      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "nav-link"%>
      </li>
      <% end%>
    </ul>
  </div>
</nav>