config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  get "new_notice" => 'posts#new_notice', as: 'new_post_notice'

  get "edit_notice/:id" => "posts#edit_notice", as: 'edit_post_notice'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root "home#index"

  get 'home/index' => 'home#index', as: 'index'

  get 'home/about' => 'home#about', as: 'about'

  get 'home/activities' => 'home#activities', as: 'activities'

  get 'home/recruit' => 'home#recruit', as: 'recruit'

  get 'home/contact' => 'home#contact', as: 'contact'

  get 'home/members' => 'home#members', as: 'members'

  get 'search' => "posts#search", as: 'search'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :edit_notice, :update, :destroy]
  before_action :check_log_in

  # GET /posts
  # GET /posts.json
  def index
      @notices = Post.where(isNotice: true).order(updated_at: :desc)
      @posts = Post.where(isNotice: false).order(updated_at: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  def new_notice
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  def edit_notice
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    permittedParams = search_params
    
    case permittedParams[:select]
    when "title"
      @notices = Post.where(title: permittedParams[:q]).where(isNotice: true).order(updated_at: :desc)
      @posts = Post.where(title: permittedParams[:q]).where(isNotice: false).order(updated_at: :desc) 
    when "name"
      @notices = User.where(name: permittedParams[:q]).first.posts.where(isNotice: true).order(updated_at: :desc)
      @posts = User.where(name: permittedParams[:q]).first.posts.where(isNotice: false).order(updated_at: :desc)
    when "email"
      @notices = User.where(email: permittedParams[:q]).first.posts.where(isNotice: true).order(updated_at: :desc)
      @posts = User.where(email: permittedParams[:q]).first.posts.where(isNotice: false).order(updated_at: :desc)
    else
      @notices = Post.where(isNotice: true).order(updated_at: :desc)
      @posts = Post.where(isNotice: false).order(updated_at: :desc)
    end
    render 'index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :user_id, :content, :isNotice)
    end

    def search_params
        params.require(:search).permit(:q, :select)
    end

    def check_log_in
      unless user_signed_in?
        redirect_to new_user_session_path
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class= "d-flex flex-column align-items-center py-5">
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title, class: "input-group" %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, id: :post_user_id,value: current_user.id %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :post_content, class: "input-group" %>
  </div>

  <div class="field">
    <%= form.hidden_field :isNotice, id: :post_isNotice,value: isNotice %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary mt-3', style: "padding-top: 6px;" %>
  </div>
<% end %>
</div>

app/views/posts/edit.html.erb
<div class= "d-flex flex-column align-items-center py-5">
<h1>글 편집</h1>

<%= render 'form', post: @post, isNotice: false %>
<p><%= link_to 'Show', @post, class: "btn btn-primary", style: "padding-top: 6px;" %>
<%= link_to 'Back', posts_path, class: "btn btn-secondary", style: "padding-top: 6px;" %></p>
</div>

app/views/posts/edit_notice.html.erb
<div class= "d-flex flex-column align-items-center py-5">
<h1>E d i t N o t i c e</h1>

<%= render 'form', post: @post, isNotice: true %>

<p><%= link_to 'Show', @post, class: "btn btn-primary", style: "padding-top: 6px;" %>
<%= link_to 'Back', posts_path, class: "btn btn-secondary", style: "padding-top: 6px;"  %></p>
</div>

app/views/posts/index.html.erb
<div class= "d-flex flex-column align-items-center py-5 contact" style="height: 1000px;">
<p id="notice"><%= notice %></p>
<h1 class="text-white">L O U N G E</h1>

<div>
  <table class="table table-borderless table-hover mt-5" style="width: 500px;">
    <thead>
      <tr class="border-bottom">
        <th class="text-white" scope="col">Title</th>
        <th class="text-white">Name</th>
        <th class="text-white">Comments</th>
      </tr>
    </thead>

    <tbody class="border-bottom text-secondary">
      <% @notices.each do |notice| %>
        <tr>
          <td style="width:100%"><%= link_to notice.title, notice, class:"text-warning" %></td>
          <td><%= notice.user.name %></td>
          <td><%= notice.comments.count %></td>
        </tr>
      <% end %>
    </tbody>  
    <tbody class="text-secondary">
      <% @posts.each do |post| %>
        <tr>
          <td><%= link_to post.title, post, class:"text-white" %></td>
          <td><%= post.user.name %></td>
          <td><%= post.comments.count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<div class="mt-4 mb-3">
<%= form_tag search_path, method: :get do %>
  <%= select_tag("search[select]", options_for_select([["제목","title"],["작성자 이름","name"],["작성자 이메일","email"]],"title" )) %>
  <%= text_field_tag "search[q]","",style:"opacity:0.4;border-radius:7px" %>
  <%= submit_tag("SEARCH", class:"btn btn-outline-warning text-white", style: "padding-top: 6px;") %>
<% end %>
</div>


<div><%= link_to('WRITE', new_post_path, class: "btn btn-outline-warning text-white", style: "padding-top: 6px;") %> 
<%= link_to('NOTICE', new_post_notice_path, class: "btn btn-outline-warning text-white", style: "padding-top: 6px;")%>
<% if current_user.try(:admin?) %>
  <%= link_to('ADMIN', admin_root_path, class: "btn btn-outline-warning text-white", style: "padding-top: 6px;" )%>
<% end %></div>
</div>

app/views/posts/new.html.erb
<div class= "d-flex flex-column align-items-center py-5">

<h1>New Post</h1>

<%= render 'form', post: @post, isNotice: false%>

<%= link_to 'Back', posts_path, class: "btn btn-secondary", style: "padding-top: 6px;" %>

</div>

app/views/posts/new_notice.html.erb
<div class= "d-flex flex-column align-items-center py-5">
<h1>New Notice</h1>

<%= render 'form', post: @post, isNotice: true %>

<%= link_to 'Back', posts_path, class: "btn btn-secondary", style: "padding-top: 6px;"  %>
</div>

app/views/posts/show.html.erb
<div class= "d-flex flex-column align-items-center py-5 bg-dark text-white members about1" style="height: 1000px;">
<p id="notice"><%= notice %></p>
  <div class="row justify-content-between border-bottom mt-5" style="width: 500px;margin-top: 150px !important;">
    <div class="col-4">
    <h5 style="width:200px">
      
      <%= @post.title %>
    </h5>
    </div>
    <div class="col-4">
      <%= @post.user.name %>
    </div>
  </div>
<hr>
<br>
  <div class="border-bottom" style="width: 500px;">
    <p>
      <%= @post.content %>
    </p>
  </div>

<table class="table table-borderless mb-5" style="width: 500px;">
  <tbody>
  <tr>
    <% i = 0 %>
    <% @post.comments.each do |comment| %>
      <td><span class="badge badge-pill badge-warning"><%= i = i + 1 %></span></td>
      <td><%= comment.content %></td>
      <td><%= comment.user.name %></td>
      <td><%= link_to "delete", post_comment_path(@post.id, comment.id), method: :delete, class: "text-warning" %></td>
      <br>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
  <%= form_for Comment.new, url: post_comments_path(@post.id) do |f|%>
    <%= f.label "Comment", class: "text-white" %>
    <%= f.text_field :content %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit "작성", class: "btn btn-outline-warning text-white", style: "padding-top: 6px;"%>
  <% end%>
</div>
<br>
<p>
<%= link_to 'back', posts_path, class: "btn btn-outline-warning text-white",style: "padding-top: 6px;" %>
<%= link_to 'edit', edit_post_path(@post), class: "btn btn-outline-warning text-white", style: "padding-top: 6px;" %>
<%= link_to 'delete', notice, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-warning text-white", style: "padding-top: 6px;" %></p>
</div>